### ISSUE TITLE
Delete Google Analytics GA4 it allows MAJOR SECURITY risk by bypassing CSP Rules

### ISSUE THREAD

**Issue by summercms** [ayumi-cloud/ga4#25]
### Enhancement idea

WAIT For Google to create the PHP SDK to use GA4 API's.

Links:

https://developers.google.com/analytics/devguides/config/admin/v1#client_libraries

https://developers.google.com/analytics/devguides/reporting/data/v1#client_libraries

Also

> The **Google Analytics Reporting API v4 does not support GA4 properties**! Instead use the `Google Analytics 4 Data API`.

**Comment by ayumi-cloud** [comment]
Let RainLab plugin know as well, when they are released:

https://github.com/rainlab/googleanalytics-plugin/issues/101

**Comment by summercms** [comment]
https://issuetracker.google.com/issues/173422062

**Comment by summercms** [comment]
https://github.com/ayumi-cloud/google-cloud-php/tree/master/AnalyticsData

**Comment by summercms** [comment]
Ripping out GA4 due to major bad security issues - more details see `readme.md` switching over to using Summer CMS Analytics instead.
